fix: update-json action error

diff --git a/.github/workflows/update-json.yml b/.github/workflows/update-json.yml
--- a/.github/workflows/update-json.yml
+++ b/.github/workflows/update-json.yml
@@ -24,28 +24,23 @@ jobs:
           owner: 'tianheg'
           repository: 'blog'
           access-token: ${{ secrets.ACCESS_TOKEN }}
-      - name: Access cloned repository content
-        run: |
-          cd blog
-          ls -l
-          pwd
 
       # gen json
-      # - name: Use Node.js
-      #   uses: actions/setup-node@v2
-      #   with:
-      #     node-version: 16
-      # - run: npm install
-      # - run: node gen-json.js
-      # - name: Commit files
-      #   run: |
-      #     git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
-      #     git config --local user.name "github-actions[bot]"
-      #     git commit -m "Update json files" -a || true
-      #     # The above command will fail if no changes were present, so we ignore
-      #     # the return code.
-      # - name: Push changes
-      #   uses: tianheg/github-actions@push
-      #   with:
-      #     github_token: ${{ secrets.GITHUB_TOKEN }}
-      #     branch: ${{ github.ref }}
+      - name: Use Node.js
+        uses: actions/setup-node@v2
+        with:
+          node-version: 16
+      - run: npm install
+      - run: node gen-json.js
+      - name: Commit files
+        run: |
+          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
+          git config --local user.name "github-actions[bot]"
+          git commit -m "Update json files" -a || true
+          # The above command will fail if no changes were present, so we ignore
+          # the return code.
+      - name: Push changes
+        uses: tianheg/github-actions@push
+        with:
+          github_token: ${{ secrets.GITHUB_TOKEN }}
+          branch: ${{ github.ref }}
