fix: action syntax

diff --git a/.github/workflows/update-json.yml b/.github/workflows/update-json.yml
--- a/.github/workflows/update-json.yml
+++ b/.github/workflows/update-json.yml
@@ -23,14 +23,14 @@ jobs:
       - run: npm install
       - run: node gen-json.js
       - name: Commit files
-      run: |
-        git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
-        git config --local user.name "github-actions[bot]"
-        git commit -m "Update blogs.json" -a || true
-        # The above command will fail if no changes were present, so we ignore
-        # the return code.
-    - name: Push changes
-      uses: tianheg/github-actions@push
-      with:
-        github_token: ${{ secrets.GITHUB_TOKEN }}
-        branch: ${{ github.ref }}
+        run: |
+          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
+          git config --local user.name "github-actions[bot]"
+          git commit -m "Update blogs.json" -a || true
+          # The above command will fail if no changes were present, so we ignore
+          # the return code.
+      - name: Push changes
+        uses: tianheg/github-actions@push
+        with:
+          github_token: ${{ secrets.GITHUB_TOKEN }}
+          branch: ${{ github.ref }}
